### ISSUE TITLE
Add fuzzer pass-through config to tester.toml

### ISSUE THREAD

**Issue by MattWindsor91** [MattWindsor91/act-tester#69]
This issue tracks exposing the configurable bits of `act.conf` (and any other fuzzer we may support in the future) through the `tester.toml` file.  This would need:

- an idea of fuzzer configurability (probably letting us disable fuzzing entirely);
- some additional code in the act.conf maker;
- some thought perhaps as to how to make this generic (but not too much thought, YAGNI etc).

This might look as follows (assuming a fix to #28):

```toml
[fuzz]
  style = "act"
  run.cmd = "act-fuzz"
  run.args = [ "-v" ] # ideally there'd be a 'run.verbose' flag or something, but this is an example
  [fuzz.config]
    params."action.cap.lower" = 20
    params."action.cap.upper" = 200
    flags."action.pick-extra" = "100:1"
```
